### ISSUE TITLE
 Scanning qrcode with APP is always loading

### ISSUE THREAD

**Issue by simonc1232** [Shayennn/MaeManeeQR#1]
I use the QR code generated by ”MaeManeeQR“ and cannot successfully scan the code. The page is still loading. Can you help me?

**Comment by Shayennn** [comment]
Hi @simonc1232  ,

I'm sorry to say. I will be free and check this in late April.
During this time, you might help everyone by fix it then create a pull request.

**Comment by Shayennn** [comment]
Hi @simonc1232,

Upon reviewing your issue, This is not related to my project. Kindly seek help from SCB Bank.

Thanks!
