### ISSUE TITLE
ModuleNotFoundError: No module named 'PyCRC'

### ISSUE THREAD

**Issue by WorkBoonyarit** [Shayennn/MaeManeeQR#3]
ModuleNotFoundError: No module named 'PyCRC'
```
pip uninstall PyCRC
pip install pythoncrc
https://stackoverflow.com/questions/65751909/no-module-named-pycrc
```

**Comment by Shayennn** [comment]
Hi @WorkBoonyarit,

I have a big update in this repo, please kindly review it and try to use it.

Thanks for your interest in my project.
